name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mysql-migrate

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Gerar timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Autenticar no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar BuildKit com Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e push da imagem com cache
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/mysql-migrate:latest
            ghcr.io/${{ env.OWNER_LOWER }}/mysql-migrate:cache
            ghcr.io/${{ env.OWNER_LOWER }}/mysql-migrate:${{ steps.timestamp.outputs.timestamp }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LOWER }}/mysql-migrate:cache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LOWER }}/mysql-migrate:cache,mode=max
